name: Build
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch
        run: |
          export DENEME=${{ secrets.DENEME }}
          echo "current path: $(pwd)"
          python /home/runner/work/test/test/x.py          
