name: Build
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch
        run: |
          echo "current path: $(pwd)"
