name: Workflow1
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  one:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run coverage test
        run: |
          echo "Current Path: $(pwd)"
  two:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run coverage test
        run: |
          echo "Current Path: $(pwd)"
