# name: Publish Docker image
# on:
#   push:
#     branches: [ main ]
# jobs:
#   push_to_registry:
# #     name: Push Docker image to Docker Hub
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Check out the repo
# #         uses: actions/checkout@v2

# #       - name: Log in to Docker Hub
# #         uses: docker/login-action@v1
# #         with:
# #           username: ${{ secrets.DOCKERHUB_USERNAME }}
# #           password: ${{ secrets.DOCKERHUB_TOKEN }}

# #       - name: Push to Docker Hub
# #         uses: docker/build-push-action@v2
# #         with:
# #           push: true
# #           tags: docker_hub_name/image_name:latest
# #           secrets: |
# #             "MYSQL_ACCESS_DATA_HOST=${{ secrets.MYSQL_ACCESS_DATA_HOST}}"
# #             "MYSQL_ACCESS_DATA_USER=${{ secrets.MYSQL_ACCESS_DATA_USER}}"
# #             "MYSQL_ACCESS_DATA_PASSWORD=${{ secrets.MYSQL_ACCESS_DATA_PASSWORD}}"
#   - name: Build & Push image
#       uses: docker/build-push-action@v2
#       with:
#         file: /server/Dockerfile
#         secrets: | 
#           "MYSQL_ACCESS_DATA_HOST=${{ secrets.MYSQL_ACCESS_DATA_HOST}}"
#           "MYSQL_ACCESS_DATA_USER=${{ secrets.MYSQL_ACCESS_DATA_USER}}"
#           "MYSQL_ACCESS_DATA_PASSWORD=${{ secrets.MYSQL_ACCESS_DATA_PASSWORD}}"
#         push: true
#         tags: ${{ steps.ecr-login.outputs.registry }}/lcm-backend:latest