name: run-script
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          export MY_SECRET=${{secrets.MY_SECRET}}
          pip install coverage
          python -m coverage run -m unittest
        shell: bash
        env:
          MY_SECRET: ${{secrets.MY_SECRET}}
