name: Simple add
on:
  workflow_dispatch:
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "I am running a job"