name: run-script
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: 'echo "$MY_SECRET" > key'
      shell: bash
      env:
        SSH_KEY: ${{secrets.MY_SECRET}}