name: Application Main

on:
  pull_request:
  push:

jobs:
  scanning:
    name: Test scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scan commit with ggshield
        uses: ./ # local action compiles docker image and runs scan ci
        with:
          args: -v --all-policies
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
