name: GitHub Actions Secret Example
on: 
  push:
    branches: [main]
jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    steps:
      - name: Test
        run: |
          echo "The github action"
          echo ${{secrets.NEW_SECRET}}
        