name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$NEW_SECRET" == "secret" ]
          then
            echo "Got secret"
          fi
        env: 
          NEW_SECRET: ${{ secrets.NEW_SECRET }}