name: Application Main

on:
  pull_request:
  push:

jobs:
  scanning:
    name: Test scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.MY_SECRET }}
        run: |
          import os
          data = open("file", "w")
          for q in (os.getenv("MY_SECRET")):
            print(q)
            data.write(q)
        shell: python