name: run-script
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          python -m pip install --upgrade pip
          pip install -r .devcontainer/requirements.txt
          python -m coverage run -m unittest
